default_platform(:ios)

platform :ios do
  desc "Run Unit tests"
  lane :tests do |options|
    target = options[:target] || "App"
    
    run_tests(workspace: "src/Recipes.xcworkspace", 
              device: "iPhone 17 (26.1)",
              scheme: target, 
              code_coverage: true)
  end

  lane :tests_coverage do
    xcov(
      workspace: "src/Recipes.xcworkspace",
      scheme: "App",
      output_directory: "fastlane/xcov_output",
      minimum_coverage_percentage: 80.0
    )  
  end
end
