import ProjectDescription
import Foundation
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: "Recipes",
    projects: [
        "./Projects/App",
        "./Projects/DependencyInjection",
    ],
    schemes: [],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)

