# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipeApp' do
  pod 'SwiftLint'
  pod 'Alamofire'
  pod 'SDWebImage/MapKit'

  target 'RecipeAppTests' do
    inherit! :search_paths
    pod 'Mocker'
  end

end
