# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipeApp' do
  pod 'SwiftLint'

  target 'RecipeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
