name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Cocoa
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: RecipeApp/Podfile.lock
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.171.0
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Change Directory to App Folder
        run: cd RecipeApp
      - name: Install Bundles
        run: bundle install
      - name: Run tests
        run: |
          pwd
          bundle exec fastlane tests
