name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Cocoa
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: RecipeApp/Podfile.lock
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.171.0
      - name: Install Bundles
        run: cd RecipeApp && bundle install
      - name: Run tests
        run: fastlane tests
