name: Main status

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-12
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 100
      - name: Install pods
        run: cd RecipeApp && pod install
      - name: Install Bundles
        run: cd RecipeApp && bundle install
      - name: Run tests
        run: cd RecipeApp && bundle exec fastlane tests
      - name: Run code coverage
        run: cd RecipeApp && bundle exec fastlane tests_coverage
